---
name: Code test
on:
  push:
    branches:
      - "*"
      - "!releases/**"
    paths-ignore:
      - "docs/**"
      - "lab-examples/**"
      - "mkdocs.yml"
      - "README.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      # create fake default config of srl for tests to validate path
      - run: sudo mkdir -p /etc/containerlab/templates/srl && sudo touch /etc/containerlab/templates/srl/srlconfig.tpl
      - run: go test -cover ./...
        env:
          CGO_ENABLED: 0

  staticcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Staticcheck
        run: |
          go get -u honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...
        env:
          CGO_ENABLED: 0
